aragon/AGPs

AGPs/A1-2019.md

This is a Finance track AGP, following [our Flock proposal](https://github.com/aragon/flock/pull/1).

Aragon Flock proposal: Aragon One

---

README.md

Add link to wiki governance page to README

---

AGPs/AGP-41.md
AGPs/AGP-XX.md

Excited to put this proposal forward for the consideration of the Aragon community! The proposal aims to strengthen the relationship between the Aragon ecosystem and the Web3 Foundation. While diversifying the Aragon Association holdings, Aragon will gain the possibility of leveraging the Polkadot technology.

Aragon Portfolio Diversification - Acquisition of DOTs

---

editorial_review.md

Documents how an AGP Editor fulfils their duties.

Create AGP Editorial Review documentation

---

AGPs/AGP-0.md
AGPs/AGP-10.md
AGPs/AGP-11.md
AGPs/AGP-12.md
AGPs/AGP-14.md
AGPs/AGP-16.md
AGPs/AGP-17.md
AGPs/AGP-18.md
AGPs/AGP-19.md
AGPs/AGP-28.md
AGPs/AGP-30.md
AGPs/AGP-34.md
AGPs/AGP-35.md
AGPs/AGP-37.md
AGPs/AGP-40.md
AGPs/AGP-41.md
AGPs/AGP-43.md
AGPs/AGP-5.md
AGPs/AGP-7.md
AGPs/AGP-8.md
AGPs/AGP-9.md
templates/association_template.md
templates/finance_template.md
templates/meta_template.md
templates/proclamation_template.md

Add title headers to AGPs and templates

---

AGPs/AGP-66.md
AGPs/AGP-F.md

We're excited to have Aragon as part of Panvala. Aragon is a key part of the broad community of teams and projects in the Ethereum ecosystem that work on common infrastructure directly or fund that work through grants. Panvala is designed to acknowledge those teams and give them the tools to incentivize more teams to join them.

AGP-66: Panvala Launch Partnership

---

AGPs/AGP-73.md
AGPs/AGP-I.md

Discussion thread:  https://forum.aragon.org/t/autark-flock-agp-for-anv-3/1059
Awaiting the Association to merge our Flock PR:
https://github.com/aragon/flock/pull/21
Then we can include the correct hash in this AGP and this can move it to Stage IV.
cc @stefanobernardi 
I'm not sure how much more we want to give for last minute community feedback revisions, before getting the Flock PR merged & proposal commit hash.

Create AGP-73: Flock Funding for Autark

---

AGPs/AGP-64.md
AGPs/AGP-D.md

Discussion thread: https://forum.aragon.org/t/agp-discussion-support-quiet-ending-voting/1100/3

AGP-64: Support Quiet Ending Voting

---

AGPs/AGP-59.md
AGPs/AGP-A.md

Discussion thread: https://forum.aragon.org/t/agp-discussion-community-review-period/986

Create AGP-59: Community Review Period

---

AGPs/AGP-67.md
AGPs/AGP-G.md

Discussion thread: https://forum.aragon.org/t/agp-discussion-2019-aragon-events-multisig-budget/1103/2

AGP-67: 2019 Aragon Events Multisig Budget

---

AGPs/AGP-72.md
AGPs/AGP-XX.md

Forum Discussion: https://forum.aragon.org/t/frame-flock-proposal-for-anv-3/1085

AGP-72: Frame Finance Proposal

---

AGPs/AGP-75.md
AGPs/AGP-M.md

Discussion thread: https://forum.aragon.org/t/agp-idea-adding-the-survey-app-to-the-aragon-network-dao-for-signaling/1094

AGP-75: The Aragon Governance Survey Process

---

AGPs/AGP-61.md
AGPs/AGP-B.md

Discussion thread: https://forum.aragon.org/t/agp-discussion-modify-aragon-network-fiscal-year/987

AGP-61: Modify Aragon Network Fiscal Year

---

AGPs/AGP-59.md
AGPs/AGP-61.md
AGPs/AGP-64.md
AGPs/AGP-66.md
AGPs/AGP-67.md
AGPs/AGP-70.md
AGPs/AGP-71.md
AGPs/AGP-72.md
AGPs/AGP-73.md
AGPs/AGP-74.md
AGPs/AGP-75.md

This PR updates the status of AGPs submitted for ANV-3 according to the [results of the review vote](https://mainnet.aragon.org/#/associationboard/0xc9cae3ba406c96f4a6e92aea68b8589781222cbe) by the Aragon Association Board of Directors.

Update AGP status

---

AGPs/AGP-CS.md

Thread discussing this AGP can be on the [Aragon Forum](https://forum.aragon.org/t/agp-discussion-develop-aragon-chain/1337)

Create AGP-CS: Develop Aragon Chain

---

AGPs/AGP-103.md
AGPs/AGP-Y.md

AGP discussion thread: https://forum.aragon.org/t/agp-discussion-annual-budget-for-the-aragon-network/1285

Create AGP-103: Aragon Network Budget

---

AGPs/AGP-112.md
AGPs/AGP-anteater.md

This proposal was originally created and finalized in PR https://github.com/aragon/AGPs/pull/85
A technical error has caused the original PR to be unable to be edited. This PR intends to fix this error.
Original comment by @anteater0x:
> Discussion thread: https://forum.aragon.org/t/agp-discussion-oppose-any-change-to-ethereums-mining-algorithm-before-ethereum-2-0/1284

Create AGP-112: Oppose any change to Ethereum's mining algorithm before Ethereum 2.0

---

AGPs/AGP-88.md
AGPs/AGP-CRDAO.md

An AGP to create and fund the CRDAO! 🦅

AGP-88: Community Rewards DAO

---

AGPs/AGP-1Hive-Sponsorship.md
AGPs/AGP-90.md

A proposal to sponsor the 1Hive DAO's ongoing contributions to the Aragon community.

AGP-90: 1Hive DAO Sponsorship Proposal

---

AGPs/AGP-105.md
AGPs/AGP-LD2.md

AGP-105: Allow finance proposals that could otherwise fit in Nest or Flock

---

AGPs/AGP-118.md
AGPs/AGP-Comprehensive-Aragon-Legal-Review-Program.md

[Old PR for this AGP](https://github.com/aragon/AGPs/pull/101) broke due to technical difficulties.
Was told by AGP Editor @john-light to resubmit AGP PR in [this](https://forum.aragon.org/t/call-for-an-emergency-vote-to-push-back-every-stage-of-anv4-by-1-week/1356/26) forum comment.

AGP-118: Aragon Comprehensive Legal Review Program

---

AGPs/AGP-1.md
AGPs/AGP-106.md

Fix markdown formatting on AGP-106

---

AGPs/AGP-120.md
AGPs/AGP-130.md

Proposal to Sponsorship Aragon Mesh.
TODO:

AGP-130: Aragon Mesh Sponsorship

---

AGPs/AGP-153.md
AGPs/AGP-JL1.md
votes/2019-12-11-ANV-5.md

Discussion thread: https://forum.aragon.org/t/discussion-thread-for-agp-reduce-the-judgment-powers-of-agp-editors/1490

AGP-153: Reduce the judgment powers of AGP Editors

---

AGPs/AGP-155.md
AGPs/AGP-TBD.md

Forum discussion:
https://forum.aragon.org/t/agp-discussion-sunsetting-the-agp-process/1867

AGP-155: Sunsetting the AGP process
